import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import {
	ASSET_KEY,
	PARENT_KEY,
	PROJECT_KEY,
	QUERY_KEY,
	WORKSPACE_KEY,
} from './constant/keys';
import { setIds } from './documents/editor/EditorContext';
import decodeParams from './utils/decodeParams';

const HARDCODED_QUERY_PARAM = 'eyJ3IjoicFQ5dkFMeDIzIiwicGEiOiJWNTU2YnA3QjIiLCJhIjoiOTVhMjZhYjktMmU4OC00NGFmLWI2MTUtODVhMDQxNjQ1NzNiIn0=';
const HARDCODED_ACCESS_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJEN0t1VlR0eEQ3a2pUbEFkb3Q0WVFMTk90UUNEWWJGZnFEeU9URGJ3VWdjIn0.eyJleHAiOjE3NzQ2OTk2MDgsImlhdCI6MTc3MjEwNzYwOCwianRpIjoiZGM3MGYxYmUtM2YwMi00NGM3LTg1ZGMtOWJhOGQ2OTFkYzhkIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5nb2ZvLmFwcC9yZWFsbXMvb3V0ZSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI4ZWU4YzQ1MS0zNGIyLTQ0ZGEtOGQxZi0xNzkzMTMyNDg0OGYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvdXRlLWljLWNhbnZhcyIsInNpZCI6IjBmNWVlZDU0LTljYTUtNDU1NC1hM2FkLTA0ZTQ3YzJlOTI0OCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9vdXRlLmFwcCIsImh0dHBzOi8vdWx0aW1hdGUtc2hlZXQtc2hhcmluZy5kMmF5OWU5cWgxOGl1Mi5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vd2NsLm91dGUuYXBwIiwiaHR0cHM6Ly9hdXRoLm91dGUuYXBwIiwiaHR0cHM6Ly9mYy1lYzIub3V0ZS5hcHAiLCJodHRwczovL2NhbnZhcy12Mi5kM2pneXNkdTcyYnRpei5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vZWUzZjAwOTctNmU2NS00ZGU1LWI5OTktNzljNzM5YjE2YjZiLTAwLTJ4bm55cmd5emZsd3ouc2lza28ucmVwbGl0LmRldiIsImh0dHBzOi8vcmFodWwxMjMudHVubmVsLnBoYXJtYWN5YXBwLmluIiwiaHR0cHM6Ly9pY2Mub3V0ZS5hcHAiLCJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJodHRwOi8vbG9jYWxob3N0OjUxNzQiLCJodHRwczovL21haWwub3V0ZS5hcHAiLCJodHRwczovL2hhbmRsZS1vYXV0aC5vdXRlLmFwcCIsImh0dHBzOi8vY29udGVudC5vdXRlLmFwcCIsImh0dHBzOi8vY29tbWFuZGJhci1wb2MuZDNqZ3lzZHU3MmJ0aXouYW1wbGlmeWFwcC5jb20iLCJodHRwczovL2VtYWlsLm91dGUuYXBwIiwiaHR0cHM6Ly9hZ2VudC5vdXRlLmFwcCIsImh0dHBzOi8vY3Vyc29yLWNvZGUuZDFra2t3dHg3N2drNmguYW1wbGlmeWFwcC5jb20iLCJodHRwczovL3d3dy50aW55Y29tbWFuZC5jb20iLCJodHRwczovL2ljbC5vdXRlLmFwcCIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMiIsImh0dHBzOi8vaWMub3V0ZS5hcHAiLCJodHRwczovL3V4bWFpbC5vdXRlLmFwcCIsImh0dHBzOi8vdGVtcGxhdGUub3V0ZS5hcHAiLCJodHRwczovL2NoYW5kLXByYXRpay5kMWtra3d0eDc3Z2s2aC5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vZGV2ZWxvcC5kM2NyMTRvajhzam1tYS5hbXBsaWZ5YXBwLmNvbSIsIioiLCJodHRwOi8vbG9jYWxob3N0OjMwMDEiLCJodHRwczovL2Ntcy5vdXRlLmFwcCIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImh0dHBzOi8vc2hlZXRzLm91dGUuYXBwIiwiaHR0cHM6Ly9jaHVuay1yZXZlcnQuZDNqZ3lzZHU3MmJ0aXouYW1wbGlmeWFwcC5jb20iLCJodHRwczovL2FjY291bnQub3V0ZS5hcHAiLCJodHRwczovL2NvbnRlbnQuZ29mby5hcHAiLCJodHRwczovL2ZjLm91dGUuYXBwIiwiaHR0cHM6Ly93Yy5vdXRlLmFwcCIsImh0dHBzOi8vbG9naW4ub3V0ZS5hcHAiLCJodHRwczovL3NoZWV0LXYxLm91dGUuYXBwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtb3V0ZSIsInVtYV9hdXRob3JpemF0aW9uIiwicGFydG5lci1hZG1pbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsImRlbGV0ZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiQWJoYXkgR3VwdGEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmhheS5ndXB0YUBpbnN0aW5jdGlubm92YXRpb25zLmNvbSIsImdpdmVuX25hbWUiOiJBYmhheSIsImZhbWlseV9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFiaGF5Lmd1cHRhQGluc3RpbmN0aW5ub3ZhdGlvbnMuY29tIn0.BG4HN_fyOEHIelElXHAEgC40J-BamQ8SLOfQPt7uxoZSOdygrjMk40SVA029BgzNCX_w272cQAuDvdHC2Nb3lNumx0JX6nUdOp73IpqcLKmutTVHqMTXkHnokSFk6K6zd1kf5yph5ODRXx-ua8tGjMUzJngUdJjN0dH2la_jczFOiRTr-FlgJ-fisjs4IbqPSKBF-OWQJdKKAfWu9mIOV8e8w61fusA2ztTcDErWNkQPzALGoZckT-4Fx1QicoBMmf6hJhJsZug_a83pZx-MC9vq5_zsNSVfsbFWB3IJks90aJw1H0BX_hWTST9GF7SFRdQAN80vt8WsoyIxcuEmUQ';

function AuthRoute({ component: Component }) {
	const [valid, setValid] = useState(false);

	const [searchParams] = useSearchParams();

	const navigate = useNavigate();

	const validateSession = useCallback(() => {
		setValid(false);
		const queryParam = searchParams.get(QUERY_KEY) || HARDCODED_QUERY_PARAM;
		const params = decodeParams(queryParam) || {};

		setIds({
			workspaceId: params[WORKSPACE_KEY],
			projectId: params[PROJECT_KEY],
			parentId: params[PARENT_KEY],
			assetId: params[ASSET_KEY],
		});
		setValid(true);
		window.accessToken = HARDCODED_ACCESS_TOKEN;
	}, [searchParams]);

	useEffect(() => {
		if (!searchParams.get(QUERY_KEY)) {
			// navigate('/redirect-to-home');
			const params = new URLSearchParams(searchParams);
			params.set(QUERY_KEY, HARDCODED_QUERY_PARAM);
			navigate({
				search: params.toString(),
			}, { replace: true });
		}
	}, [navigate, searchParams]);

	useEffect(() => {
		validateSession();
	}, [validateSession]);

	return valid && <Component />;
}

export default AuthRoute;
