import React, { useCallback, useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import {
	ASSET_KEY,
	PARENT_KEY,
	PROJECT_KEY,
	QUERY_KEY,
	WORKSPACE_KEY,
} from './constant/keys';
import { setIds } from './documents/editor/EditorContext';
import decodeParams from './utils/decodeParams';

const HARD_CODED_QUERY_PARAM = 'eyJ3IjoicFQ5dkFMeDIzIiwicHIiOm51bGwsInBhIjpudWxsLCJhIjoiMTFjMzc5ODQtMGQzYi00YzUzLWFlZTctN2YwNTM3Y2QxZjM4In0=';
const HARD_CODED_ACCESS_TOKEN = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJEN0t1VlR0eEQ3a2pUbEFkb3Q0WVFMTk90UUNEWWJGZnFEeU9URGJ3VWdjIn0.eyJleHAiOjE3NzUzNjk1MTksImlhdCI6MTc3Mjc3NzUxOSwianRpIjoiZWQ2Y2UyNDYtZWJkZC00NTE1LWI2OWMtNjhjYWNhZDc0ZmFhIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5nb2ZvLmFwcC9yZWFsbXMvb3V0ZSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI4ZWU4YzQ1MS0zNGIyLTQ0ZGEtOGQxZi0xNzkzMTMyNDg0OGYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvdXRlLWljLWNhbnZhcyIsInNpZCI6ImE3ZjhhMWRjLTVlOWYtNDEwMi1hM2E1LTdkODBkMTliNDBiYiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cHM6Ly9vdXRlLmFwcCIsImh0dHBzOi8vdWx0aW1hdGUtc2hlZXQtc2hhcmluZy5kMmF5OWU5cWgxOGl1Mi5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vd2NsLm91dGUuYXBwIiwiaHR0cHM6Ly9hdXRoLm91dGUuYXBwIiwiaHR0cHM6Ly9mYy1lYzIub3V0ZS5hcHAiLCJodHRwczovL2NhbnZhcy12Mi5kM2pneXNkdTcyYnRpei5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vZWUzZjAwOTctNmU2NS00ZGU1LWI5OTktNzljNzM5YjE2YjZiLTAwLTJ4bm55cmd5emZsd3ouc2lza28ucmVwbGl0LmRldiIsImh0dHBzOi8vcmFodWwxMjMudHVubmVsLnBoYXJtYWN5YXBwLmluIiwiaHR0cHM6Ly9pY2Mub3V0ZS5hcHAiLCJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJodHRwOi8vbG9jYWxob3N0OjUxNzQiLCJodHRwczovL21haWwub3V0ZS5hcHAiLCJodHRwczovL2hhbmRsZS1vYXV0aC5vdXRlLmFwcCIsImh0dHBzOi8vY29udGVudC5vdXRlLmFwcCIsImh0dHBzOi8vY29tbWFuZGJhci1wb2MuZDNqZ3lzZHU3MmJ0aXouYW1wbGlmeWFwcC5jb20iLCJodHRwczovL2VtYWlsLm91dGUuYXBwIiwiaHR0cHM6Ly9hZ2VudC5vdXRlLmFwcCIsImh0dHBzOi8vY3Vyc29yLWNvZGUuZDFra2t3dHg3N2drNmguYW1wbGlmeWFwcC5jb20iLCJodHRwczovL3d3dy50aW55Y29tbWFuZC5jb20iLCJodHRwczovL2ljbC5vdXRlLmFwcCIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMiIsImh0dHBzOi8vaWMub3V0ZS5hcHAiLCJodHRwczovL3V4bWFpbC5vdXRlLmFwcCIsImh0dHBzOi8vdGVtcGxhdGUub3V0ZS5hcHAiLCJodHRwczovL2NoYW5kLXByYXRpay5kMWtra3d0eDc3Z2s2aC5hbXBsaWZ5YXBwLmNvbSIsImh0dHBzOi8vZGV2ZWxvcC5kM2NyMTRvajhzam1tYS5hbXBsaWZ5YXBwLmNvbSIsIioiLCJodHRwOi8vbG9jYWxob3N0OjMwMDEiLCJodHRwczovL2Ntcy5vdXRlLmFwcCIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImh0dHBzOi8vc2hlZXRzLm91dGUuYXBwIiwiaHR0cHM6Ly9jaHVuay1yZXZlcnQuZDNqZ3lzZHU3MmJ0aXouYW1wbGlmeWFwcC5jb20iLCJodHRwczovL2FjY291bnQub3V0ZS5hcHAiLCJodHRwczovL2NvbnRlbnQuZ29mby5hcHAiLCJodHRwczovL2ZjLm91dGUuYXBwIiwiaHR0cHM6Ly93Yy5vdXRlLmFwcCIsImh0dHBzOi8vbG9naW4ub3V0ZS5hcHAiLCJodHRwczovL3NoZWV0LXYxLm91dGUuYXBwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsImRlZmF1bHQtcm9sZXMtb3V0ZSIsInVtYV9hdXRob3JpemF0aW9uIiwicGFydG5lci1hZG1pbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsImRlbGV0ZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiQWJoYXkgR3VwdGEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmhheS5ndXB0YUBpbnN0aW5jdGlubm92YXRpb25zLmNvbSIsImdpdmVuX25hbWUiOiJBYmhheSIsImZhbWlseV9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFiaGF5Lmd1cHRhQGluc3RpbmN0aW5ub3ZhdGlvbnMuY29tIn0.UCQe7NjvfOqHuG8QIYpInrVR-P09JcrQH6cZIqLMGI8xU0RhQCVL4e8MfYVxEAPpKyFz_0DvnXmFJXEurhEdTtDJAR1QgVV8sfwBv76z14ZC_wlZHbJR55p08PbmxxtARh2iP9Puz0yMZKURWWjyFhydrtnPMitszQs2yVVoF7BxQw0hgFpVEz9-qqlUojOrbKCAhAZGPBgICgLWMflC49GX6Ta3O1m8h77OKLn3od9wuO7eopMNUcuDSGEe8gcs4pDRhjN2FuX6HmDtH4XXtzLlvvRnCBmAbgHVcG-qTe5a9rRFyjxAiscStTQ7WNHEB3i9FKmA1pIaC5CEKYGQlQ';

function AuthRoute({ component: Component }) {
	const [valid, setValid] = useState(false);
	const isReplit = process.env.REACT_APP_IS_REPLIT === 'true';

	const [searchParams] = useSearchParams();

	const navigate = useNavigate();

	const validateSession = useCallback(() => {
		setValid(false);
		const params = decodeParams(searchParams?.get(QUERY_KEY)) || {};

		setIds({
			workspaceId: params[WORKSPACE_KEY],
			projectId: params[PROJECT_KEY],
			parentId: params[PARENT_KEY],
			assetId: params[ASSET_KEY],
		});
		setValid(true);
	}, [searchParams]);

	useEffect(() => {
		if (!searchParams.get(QUERY_KEY)) {
			if (isReplit) {

				searchParams.set(QUERY_KEY, HARD_CODED_QUERY_PARAM);
				navigate(`${window.location.pathname}?${searchParams.toString()}`);
				window.accessToken = HARD_CODED_ACCESS_TOKEN;
			} else {
				navigate('/redirect-to-home');
			}
		}
	}, [navigate, searchParams]);

	useEffect(() => {
		validateSession();
	}, [validateSession]);

	return valid && <Component />;
}

export default AuthRoute;
